name: rojo
 
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Layout file name
        id: naming
        env:
          GIT_HASH: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
          GITHUB_ACTION_EVENT_NAME: ${{ github.event_name }}
        run: |
         CURDATETIME = $(date +'%Y-%m-%d')
         echo "output_name=Adonis_Nightly_${CURDATETIME}_${GIT_REF}_${GIT_HASH}" >> $GITHUB_OUTPUT
      # TODO: Make 'nightly' dynamic
      - uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build -o ${{ steps.naming.outputs.output_name }}.rbxm .github/build.project.json

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.naming.outputs.output_name }}
          path: ${{ steps.naming.outputs.output_name }}.rbxm

    # The following are ran for pushes, not pull requests, only.
          
      - name: Build Nightly MainModule
        if: github.repository == 'Epix-Incorporated/Adonis' && github.event_name == 'push'
        run: rojo build -o module.rbxm .github/module.deploy.project.json

      - name: Send file nightly build to Discord channel
        uses: tsickert/discord-webhook@v3.0.0
        if: github.repository == 'Epix-Incorporated/Adonis' && github.event_name == 'push'
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK }}
          filename: ${{ steps.naming.outputs.output_name }}.rbxm
          
      - name: Publish Nightly MainModule
        uses: fjogeleit/http-request-action@v1
        if: github.repository == 'Epix-Incorporated/Adonis' && github.event_name == 'push'
        with:
          url: "${{ secrets.PUBURL2 }}/?assetId=${{ secrets.NIGHTLY_MODULE_ID }}"
          method: "POST"
          contentType: "multipart/form-data"
          files: '{ "file": "module.rbxm" }'
          customHeaders: '{ "upload-secret": "${{ secrets.PUBURL2_SECRET }}" }'
          timeout: 10000