name: rojo

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      FILE_NAME: ${{ echo Adonis_Nightly_$(date +"%Y_%m_%d_%H_%M").rbxmx }}

    steps:
      - uses: actions/checkout@v1

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build .github/build.project.json -o $FILE_NAME

      - uses: actions/upload-artifact@v2
        with:
          name: model_artifact
          path: $FILE_NAME
      
      
      - name: Send file nightly build to Discord channel
        uses: sinshutu/upload-to-discord@master
        env:
           DISCORD_WEBHOOK: ${{ secrets.NIGHTLY_WEBHOOK }}
        with:
           args: $FILE_NAME
