name: update-lint

on:
  workflow_dispatch

jobs:
  update-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: Roblox/setup-foreman@v1
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Update standard library
      run: |
        selene generate-roblox-std

    - name: Setup Git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
    
    - name: Commit to repo
      run: |
        git add roblox.yml
        git commit -m "Update lint standard library"
        git push origin master